# -*- coding: utf-8 -*-
"""Matplotlib_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/157rlxGO-t5XEefTDE3sLdQZyd-P6eNhm
"""

import matplotlib.pyplot as plt
import numpy as np

# 맥 환경에서 한글이 깨져보일 수 있음
# 폰트 지정
plt.rcParams['font.family'] = 'AppleGothic' 
plt.rcParams['font.size'] = 10

"""# 기본 그래프"""

X = np.linspace(0, 2 * np.pi, 100)
Ya, Yb = np.sin(X), np.cos(X)

plt.plot(X, Ya)
plt.plot(X, Yb)

plt.title("sin과 cos") # 제목

plt.xlabel('X axis') # x축 라벨
plt.ylabel('Y axis') # y축 라벨
plt.text(5.5, -1.0, 'Hello') # 글자
plt.legend() # 범례

plt.grid(linestyle='--') # grid

plt.show()

"""# Subplots"""

fig, ax = plt.subplots(2, 1)
ax[0].plot(X, Ya, label='sin(x)')
ax[1].plot(X, Yb, label='cos(x)')

plt.show()

"""# Pie Chart"""

data = [5, 25, 50, 20]
txt = ['빵', '우유', '채소', '고기']
exp = [0.5, 0.1, 0.1, 0.1]

plt.pie(x=data, labels=txt, explode=exp, startangle=30)

"""# Bar Chart"""

data = [5.0, 25.0, 50.0, 20.0]
plt.bar(x=range(len(data)), height=data, width=0.75)
plt.show()

"""# Histogram"""

X = np.random.randn(1000)
plt.hist(x=X, bins=20, width=0.2)
plt.show()

"""# 선 그리기"""

plt.ylim(400, 0)
plt.xlim(0, 400)


x = [100, 100, 114, 146, 158, 160, 143, 112, 100]
y = [148, 138, 125, 127, 141, 156, 169, 168, 148]

line = plt.Line2D(x, y, color='red')
axes = plt.gca()
axes.add_line(line)

import matplotlib.patches as patches

r = patches.Rectangle(xy=(0, 0), width=0.5, height=0.5)
fig, ax = plt.subplots()
ax.add_patch(r)

import matplotlib.pyplot as plt
import numpy as np
import csv

csv_file = './assets2/도로교통공단_전국_사망교통사고정보.csv'
ncity = dict()

with open(csv_file, 'rt', encoding='euc-kr') as f:
    fcsv = csv.DictReader(f)
    
    for row in fcsv:
        city = row['발생지시도']
        
        if city not in ncity:
            ncity[city] = 1
        else:
            ncity[city] += 1
            
    x_names = list()
    y = list()
    
    for city, n in ncity.items():
        x_names.append(city)
        y.append(n)
        
    x = range(len(y))
    
    plt.rc('font', family='AppleGothic')
    plt.bar(x, y)
    plt.xticks(x, x_names)
    plt.show()

import pandas as pd

csv_file = './assets2/도로교통공단_전국_사망교통사고정보.csv'
ncity = dict()

data = pd.read_csv(csv_file, encoding='euc-kr')
# data
cities = np.array(data['발생지시도'])
print(cities)

for i in range(len(cities)):
    city = cities[i]
    if city not in ncity:
        ncity[city] = 1
    else:
        ncity[city] += 1
        
x_names = list()
y = list()

for city, n in ncity.items():
    x_names.append(city)
    y.append(n)

x = range(len(y))

plt.rc('font', family='AppleGothic')
plt.bar(x, y)
plt.xticks(x, x_names)
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

data = pd.read_csv('./assets2/president_heights.csv')
heights = np.array(data['height(cm)'])

# print(heights)

print('Mean height : ', heights.mean())
print('표준편차 height: ', heights.std())

# 분산(variance): 데이터와 샘플 평균 간의 거리 제곱의 평균
# 샘플 분산이 작을수록 데이터가 모여있고, 클수록 흩어져 있다.
print('분산 height : ', heights.var())


print('최고 height: ', heights.max())
print('최소 height : ', heights.min())

print('25th percentile: ', np.percentile(heights, 25))
# 1사분위

print('Median: ', np.median(heights))
# 데이터의 중앙값
print('50th percentile: ', np.percentile(heights, 50))


plt.hist(heights)
plt.title('역대 미대통령 키분포')
plt.xlabel('height(cm)')
plt.ylabel('number')

plt.show()