# -*- coding: utf-8 -*-
"""02-1-Supervised-learning-Iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12MYr0tkh_OndYcRS7CuX7Goyj95Nuuph
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

"""# Iris 꽃 분석"""

from sklearn.datasets import load_iris

iris_dataset = load_iris()

type(iris_dataset)

iris_dataset.keys()

print(iris_dataset['DESCR'][:193]) # iris_dataset.DESCR도 가능

print('Target names:', iris_dataset['target_names']) # label

print('Feature names:\n', iris_dataset['feature_names']) # feature

iris_dataset['data']

type(iris_dataset['data'])

iris_dataset['data'].shape

print('First 5 rows of data:\n', iris_dataset['data'][:5])

print('Shape of target:', iris_dataset['target'].shape)

print('target:\n', iris_dataset['target'])

"""## Training and Testing Data"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=0)

print('X_train shape:', X_train.shape)
print('y_train shape:', y_train.shape)

print('X_test shape:', X_test.shape)
print('y_test shape:', y_test.shape)

"""### Building Your First Model: k-Nearest Neighbors"""

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1)

"""- overfit: 과대적합(과적합)
- underfit: 과소적합
"""

knn.fit(X_train, y_train)

"""## Making Predictions"""

y_pred = knn.predict(X_test)
print('Test set prediction:\n', y_pred)

print('Test set score: ', np.mean(y_pred == y_test))

X_new = np.array([[5, 2.9, 1, 0.2]])
print('X_new.shape:', X_new.shape)

prediction = knn.predict(X_new)

print('Prediction:', prediction)
print('Prediction Target Name:', iris_dataset['target_names'][prediction])

