# -*- coding: utf-8 -*-
"""2_Face Recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mGsOzlhfveoMNiv9vg1GQoHsgUh9OT8N

# Face API Sample
"""

import requests
from io import BytesIO
from PIL import Image, ImageDraw, ImageFont

subscription_key = 'subscription_key'

face_api_url = 'https://daegufaceapi.cognitiveservices.azure.com/face/v1.0/detect'

image_url = 'https://how-old.net/Images/faces2/main007.jpg'

omygirl_url = 'https://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20201125083158781.jpg/melon/optimize/90'

img = Image.open(BytesIO(requests.get(omygirl_url).content))

headers = {'Ocp-Apim-Subscription-Key': subscription_key}

params = {
    'returnFaceId': 'true',
    'returnFacelandmarks': 'false', # 얼굴이정표 설정
    'returnFaceAttributes': 'age,gender,emotion'
}

data = { 'url': omygirl_url }

response = requests.post(face_api_url, params=params, headers=headers, json=data)

faces = response.json()

faces

"""## 얼굴 이정표
[얼굴이정표](https://docs.microsoft.com/ko-kr/azure/cognitive-services/face/concepts/face-detection)
[얼굴 속성 정보](https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236)
![얼굴이정표](https://docs.microsoft.com/ko-kr/azure/cognitive-services/face/images/landmarks.1.jpg)
"""

def CreateImage(faces):
    
    for face in faces:
        rect = face['faceRectangle']
        # 사각형 출력
        top = rect['top']
        left = rect['left']
        bottom = rect['height'] + top
        right = rect['width'] + left
        
        draw.rectangle(((left,top),(right,bottom)), outline='red')
        
        # 정보 작성
        fontX = left
        fontY = top - 18
        
        face_info = face['faceAttributes']
        gender = face_info['gender']
        age = face_info['age']
        
        result = 'Gender: {0} Age: {1}'.format(gender, age)
        
        draw.text((fontX, fontY), result, fill='red')

draw = ImageDraw.Draw(img)

CreateImage(faces)

img

